export const COLORS = [
  'var(--butterfly-blue)',
  'var(--sea-green)',
  'var(--cyber-yellow)',
  'var(--sky-blue)',
  'var(--slate-blue)',

  'var(--accent-blossom)',
  'var(--accent-citrus)',
  'var(--accent-lagoon)',
  'var(--accent-sky)',
  'var(--accent-aqua)',
  'var(--accent-azure)',
  'var(--accent-meadow)',
  'var(--accent-tidal)',
  'var(--accent-fern)',
  'var(--accent-olive)',
  'var(--accent-orchid)',
  'var(--accent-petal)',
  'var(--accent-mint)',
  'var(--accent-cream)',
  'var(--accent-dune)',
  'var(--accent-twilight)',
  'var(--accent-wave)',
  'var(--accent-wisteria)',
  'var(--accent-zest)',
  'var(--accent-tangerine)',
]
